### ISSUE TITLE
Consulta para ver ventas

### ISSUE THREAD

**Issue by andres174** [gabriel12QK/backend-E-Commerce#8]
Realizar las consultas necesarias para implementar la funcionalidad.

**Comment by bermeo2000** [comment]
index
![image](https://user-images.githubusercontent.com/104100468/210082512-4838e8da-c666-4b03-b743-d5b30599e595.png)
ShowVenta
![image](https://user-images.githubusercontent.com/104100468/210082773-0b097383-af22-4657-a8bf-40b1f0e2ccff.png)

![image](https://user-images.githubusercontent.com/104100468/210082845-92086e94-0d15-4d1a-bc85-8bd41af40264.png)

![image](https://user-images.githubusercontent.com/104100468/210082897-75d25221-0bf1-4497-9d67-ade9aab7634b.png)
